ALTER TABLE account_sources RENAME CONSTRAINT account_sources_stream_id_fkey TO account_cameras_stream_id_fkey;
ALTER TABLE account_sources RENAME CONSTRAINT account_sources_account_id_fkey TO account_cameras_account_id_fkey;
ALTER TABLE account_sources RENAME CONSTRAINT account_sources_stream_id_key TO account_cameras_stream_id_key;
ALTER TABLE account_sources RENAME CONSTRAINT account_sources_pkey TO account_cameras_pkey;
ALTER TABLE account_sources RENAME TO account_cameras;
