logLevel: info
rtsp: false
rtmp: false
hls: false
webrtc: false
moq: false
srt: true
srtAddress: :8890
api: true
apiAddress: :9997
metrics: false
pprof: false

authMethod: internal
authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
      - action: read
      - action: api

pathDefaults:
  source: publisher
  srtReadPassphrase: local-read-token-1234

paths:
  all_others:
